export const CREATE_FOUNDATION = "CREATE FOUNDATION";
export const CREATE_NON_PROFIT = "CREATE NON-PROFIT";
export const SEND_EMAILS = "SEND EMAILS";
export const SEE_ALL_EMAILS = "SEE ALL EMAILS";

export const TAB_FIELDS = [CREATE_FOUNDATION,
    CREATE_NON_PROFIT,
    SEND_EMAILS,
    SEE_ALL_EMAILS
]